config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    'search',   to: 'posts#search'
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :posts
  resources :result_posts,        only: [:show, :create, :destroy]
  resources :choices,             only: [:index, :create, :destroy, :show]
end

app/models/post.rb
class Post < ApplicationRecord#::Base
  belongs_to :user
  has_many :result_post, dependent: :destroy#新しく作った
  has_many :choices, dependent: :destroy#投稿時の保存先変更
  accepts_nested_attributes_for :choices
  default_scope -> { order(created_at: :desc) }
  validates :user_id,     presence: true
  validates :title,       presence: true, length: { maximum: 40  }
  validates :description, presence: true, length: { maximum: 400 }
  validates_associated :choices
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

 # def index
    #@posts = Post.all.order(created_at: :desc)
  #end
  def show
    @choice = Choice.where(post_id: params[:id])
    @count_choice_1 = ResultPost.where(post_id: params[:id], choice_id: Choice.where(post_id: params[:id]).first.id).length
    @count_choice_2 = ResultPost.where(post_id: params[:id], choice_id: Choice.where(post_id: params[:id]).second.id).length
    @post = Post.find_by(id: params[:id])
    @data = [[@choice.first.item, @count_choice_1], [@choice.second.item, @count_choice_2]] #ボタンのデータ
    ResultPost.find_by(post_id: params[:id], user_id: current_user.id)
    
    
  end

  def create
    @post = current_user.posts.build(title: params[:post][:title] , description: params[:post][:description])
     if @post.save
        @choice = Choice.create(post_id: @post.id, item: params[:post][:choice][:item_1])
                  Choice.create(post_id: @post.id, item: params[:post][:choice][:item_2])
                  
       if params[:post][:choice][:item_1] != "" && params[:post][:choice][:item_2] != ""
         if params[:post][:choice][:item_1] == params[:post][:choice][:item_2]
           flash.now[:danger] = "各選択肢には違う内容を入れてください"
           render 'new'  
         else
         flash[:success] = "Post created!"
         redirect_to post_path(@post)
         end
       else
        flash[:danger] = "選択肢が足りません"
        render "new"
       end
     else
       render "new"     
     end
  end
  
  def destroy
    @post.destroy
    flash[:success] = "Post deleted"
    redirect_to request.referrer || root_url
  end
  
  def new
    @post       = current_user.posts.build
    @choice = @post.choices.build
    @post.choices.build
  end
  
  def update
      @post = Post.find_by(id: params[:id])
      @choice1 = Choice.where(post_id: @post.id).first
      @choice2 = Choice.where(post_id: @post.id).second
      @choice = @choice1 ,@choice2
      @post.update(title: params[:post][:title] , description: params[:post][:description])
      
     if params[:post][:choice][:item_1] != "" && params[:post][:choice][:item_2] != ""
      if params[:post][:choice][:item_1] == params[:post][:choice][:item_2]
        flash.now[:danger] = "各選択肢には違う内容を入れてください"
        render 'new'
      else
      if @choice1.nil?
        Choice.create(post_id: @post.id, item: params[:post][:choice][:item_1])
      else
        @choice1.update(item: params[:post][:choice][:item_1])
      end
      if @choice2.nil?
        Choice.create(post_id: @post.id, item: params[:post][:choice][:item_2])
      else
         @choice2.update(item: params[:post][:choice][:item_2])
      end
         flash[:success] = "Post created!"
         redirect_to post_path(@post)
      end
     else
        flash.now[:danger] = "選択肢が足りません"
        render "new"
     end
  end

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true)
  end

  def search
    @q = Post.search(search_params)
    @posts = @q.result(distinct: true)
  end

  private
  
  def search_params
    params.require(:q).permit!
  end
  
  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_url if @post.nil?
  end  
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <div class="post-font">
  <%= render 'shared/error_messages', object: f.object %>
  
  <div class="form-group">
    <%= f.label :タイトル %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :詳細事項 %>
    <%= f.text_area :description, class: "form-control_1" %>
  </div>
  
  <div class="form-choice">
  <%= f.fields_for :choice do |choice| %>
    <%= f.label :選択肢１ %>
    <%= choice.text_field :item_1, class: "item_1" %>
  <% end %>
  </div>
  
  <div class="form-choice-1">
  <%= f.fields_for :choice do |choice| %>
    <%= f.label :選択肢２ %>
    <%= choice.text_field :item_2, class: "item_2" %>
  <% end %>
  </div>
  
  <div class="buttons">
  <button class="pulse">投稿</button>
  </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <span class="user"><%= link_to post.user.name, post.user %></span>
  <span class="title"><%= post.title %></span>
  <span class="description">
    <%= post.description %>
    <%= image_tag post.picture.url if post.picture? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago. 
    <% if current_user?(post.user) %>
      <%= link_to "削除", post, method: :delete,
                                  data: { confirm: "You sure?" } %>
    <% end %>                              
  </span>
</li>

app/views/posts/index.html.erb
<% provide(:title, "Index") %>
<h1>アンケート一覧</h1>
<div class="toukou">
<%= search_form_for @q do |f| %>
  <%= f.label :title, "タイトルで検索" %>
  <%= f.search_field :title_cont %>
  <%= f.submit "検索" %>
<% end %>
</div>
<table class="table table-bordered border-primary table-hover table-sm posts_table">
  <thead class="thead-dark">
    <tr>
    
      <th scope="col" style="width: 260px">投稿タイトル</th>
      <th scope="col" style="width: 100px">投稿者</th>
      <th scope="col" style="width: 190px">投稿日</th>
      <th scope="col" style="width: 190px">更新日時</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% @posts.each do |post| %>
      <div class="posts-index-item">
          <td><%= link_to(post.title,"/posts/#{post.id}") %></td>
          <td><%= post.user.name %></td>
          <td><%= post.created_at.to_s(:datetime_base) %></td>
          <td><%= post.updated_at.to_s(:datetime_base) %></td>
      </div>
    </tr>
  </tbody>
  <% end %> 
</table>

app/views/posts/new.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="post_form">
        <%= render 'form' %>
      </section>
    </div>
  </div>

app/views/posts/show.html.erb
<% provide(:title, "投稿詳細ページ") %>
<div class="container">
    <div class="row">
        <div class="col-md-10">
          <h1>アンケートの詳細</h1>
          <div class="card" style="width: 95rem;">
            <div class="card-body">
              <h3 class="card-title"><%= @post.title %></h3>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item" style="width: 95rem; word-break: break-all;"><%= @post.description %></li>
            </ul>  
          </div>
          <div class="chart">
          <%= bar_chart @data, colors: ["#4cae4c"] %>
          </div>
          <% if ResultPost.find_by(post_id: params[:id], user_id: current_user.id) %>
        
            
            <p class="warning-message"> <%= "※投票済み" %>  </p>
          <% else %>
            <%= link_to @choice.first.item, result_posts_path(choice_id: @choice.first.id, post_id: @post.id), class: "btn btn-success", method: :post%>
            <%= link_to @choice.second.item, result_posts_path(choice_id: @choice.second.id, post_id: @post.id), class: "btn btn-success", method: :post%>
          <% end %>
        </div>
    </div>
</div>